# Generated by Django 2.2 on 2020-05-25 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteBloodCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='', max_length=50, null=True, verbose_name='Пол')),
                ('analysis_date', models.DateField(verbose_name='Дата анализа')),
                ('leukocyte', models.FloatField(verbose_name='Лейкоциты')),
                ('erythrocyte', models.FloatField(verbose_name='Эритроциты')),
                ('hemoglobin', models.IntegerField(verbose_name='Гемоглобин')),
                ('hematocrit', models.FloatField(verbose_name='Гематокрит')),
                ('sed_rate', models.IntegerField(verbose_name='СОЭ')),
                ('type', models.IntegerField()),
                ('sum', models.FloatField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Общий анализ крови',
                'verbose_name_plural': 'Общий анализ крови',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='ThreeDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutrophil', models.FloatField(verbose_name='Нейтрофилы')),
                ('lymphocyte', models.FloatField(verbose_name='Лимфоциты')),
                ('monocyte', models.FloatField(verbose_name='Моноциты')),
                ('value_type', models.CharField(choices=[('relative', 'Относительное'), ('absolute', 'Абсолютное')], default='relative', max_length=50, verbose_name='Тип значения результатов')),
                ('cbc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.CompleteBloodCount', verbose_name='Общий анализ крови')),
            ],
            options={
                'verbose_name': 'Лейкоцитарная формула класса 3-диф',
                'verbose_name_plural': 'Лейкоцитарная формула класса 3-диф',
            },
        ),
        migrations.CreateModel(
            name='FiveDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutrophil', models.FloatField(verbose_name='Нейтрофилы')),
                ('lymphocyte', models.FloatField(verbose_name='Лимфоциты')),
                ('monocyte', models.FloatField(verbose_name='Моноциты')),
                ('eosinophil', models.FloatField(verbose_name='Эозинофилы')),
                ('basophil', models.FloatField(verbose_name='Базофилы')),
                ('value_type', models.CharField(choices=[('relative', 'Относительное'), ('absolute', 'Абсолютное')], default='relative', max_length=50, verbose_name='Тип значения результатов')),
                ('cbc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.CompleteBloodCount', verbose_name='Общий анализ крови')),
            ],
            options={
                'verbose_name': 'Лейкоцитарная формула класса 5-диф',
                'verbose_name_plural': 'Лейкоцитарная формула класса 5-диф',
            },
        ),
        migrations.CreateModel(
            name='BloodSmear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promyelocyte', models.FloatField(verbose_name='Промиелоциты')),
                ('myelocyte', models.FloatField(verbose_name='Миелоциты')),
                ('metamyelocyte', models.FloatField(verbose_name='Метамиелоциты')),
                ('banded_neutrophil', models.FloatField(verbose_name='Палочкоядерные нейтрофилы')),
                ('segmented_neutrophil', models.FloatField(verbose_name='Сегментоядерные нейтрофилы')),
                ('lymphocyte', models.FloatField(verbose_name='Лимфоциты')),
                ('monocyte', models.FloatField(verbose_name='Моноциты')),
                ('eosinophil', models.FloatField(verbose_name='Эозинофилы')),
                ('basophil', models.FloatField(verbose_name='Базофилы')),
                ('plasma_cell', models.FloatField(verbose_name='Плазмациты')),
                ('value_type', models.CharField(choices=[('relative', 'Относительное'), ('absolute', 'Абсолютное')], default='relative', max_length=50, verbose_name='Тип значения результатов')),
                ('cbc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.CompleteBloodCount', verbose_name='Общий анализ крови')),
            ],
            options={
                'verbose_name': 'Микроскопия мазка крови',
                'verbose_name_plural': 'Микроскопия мазка крови',
                'ordering': ['-cbc__analysis_date'],
            },
        ),
    ]
