# Generated by Django 2.2 on 2020-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0002_auto_20200527_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completebloodcount',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='', max_length=50, verbose_name='Пол'),
        ),
    ]
