# Generated by Django 2.2 on 2020-05-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0003_auto_20200531_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsmear',
            name='cbc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_smear', to='cbc.CompleteBloodCount', verbose_name='Общий анализ крови'),
        ),
        migrations.AlterField(
            model_name='fivediff',
            name='cbc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='five_diff', to='cbc.CompleteBloodCount', verbose_name='Общий анализ крови'),
        ),
        migrations.AlterField(
            model_name='threediff',
            name='cbc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three_diff', to='cbc.CompleteBloodCount', verbose_name='Общий анализ крови'),
        ),
    ]
