# Generated by Django 2.2 on 2020-06-02 17:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patient.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(default='', max_length=255, null=True, verbose_name='Фамилия')),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='', max_length=50, null=True, verbose_name='Пол')),
                ('date_of_birth', models.DateField(default=datetime.datetime.now, null=True, verbose_name='День рождения')),
                ('phone', models.CharField(default='', max_length=255, null=True, validators=[patient.validators.PhoneRegexValidator()], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Email для связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациент',
            },
        ),
    ]
