# Generated by Django 2.2 on 2020-06-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tos',
            field=models.BooleanField(default=True, verbose_name='Я согласен на обработку персональных данных'),
            preserve_default=False,
        ),
    ]
